import React from 'react'
import f3 from '../assets/f3.webp'

export default function Fpage3() {
  return (
    <div>
      <img className='w-[65%] mx-auto h-[30%]' src={f3} alt="" />
      <p className='w-[80%] text-slate-600 mt-10 mx-auto' >The rumours were true: after three transformational years at Chloé, Gabriela Hearst is stepping down as its creative director, the brand has confirmed. Her last collection will be for Spring/Summer 2024, presented during Paris Fashion Week on 28 September. <br /> <br /> The Uruguayan designer presented her first collection for Richemont-owned Chloé in March 2021, carrying over her sustainability ethos from her namesake brand. At Chloé, her focus on sustainability — supported by president and CEO Riccardo Bellini — has borne fruit. The company achieved B Corp status in October 2021, introduced a social impact measurement tool in 2022, and launched a resale programme using digital IDs for improved transparency in 2023. <br /> <br /> Most recently, Hearst worked on a womenswear capsule collection with Atelier Jolie, Angelina Jolie’s new fashion brand, which highlights the work of artisans, and uses deadstock and lower-impact materials. Further details, including its release date, have yet to be announced. <br /> “Gabriela has brought great energy and a dynamic creative vision to her role at Chloé, contributing to a period of significant progress for the business, and writing a powerful new chapter in the story of our maison,” Bellini said in a statement. “I look forward to the presentation of the SS24 collection as the culmination of her Chloé journey, which will be a celebration of joy and creativity. I wish her much success and happiness as she focuses on her next creative endeavour.” <br />Hearst has remained at the helm of her namesake brand, established in 2015, which she has continued to show during New York Fashion Week. In 2019, LVMH Luxury Ventures, the conglomerate’s investment arm, took a minority stake in her brand. She was appointed at Chloé in December 2020. <br /> “I am grateful to have been part of the incredible team laying strong foundations for a purpose-driven future for fashion, and I am so proud of the positive change we have collectively achieved in developing a business and design perspective that puts our people and our environment first,” Hearst said in a statement. “Very few houses have such a history of strong female leaders who have each made their unique contribution to the maison, under the inspirational legacy of its founder Gaby Aghion. I feel empowered and excited about the work done at Chloé and, moreover, to leave a clear message that a woman can do it all and have fun while at it.” </p>
      <p className='w-[80%] mx-auto mt-5 text-2xl font-bold'>By LAURE GUILBAULT</p>
    </div>
  )
}
