import React from 'react'
import f2 from '../assets/f2.webp'

export default function Fpage2() {
  return (
    <div>
      <img className='w-[65%] mx-auto h-[30%]' src={f2} alt="" />
      <p className='w-[80%] text-slate-600 mt-10 mx-auto' >Celebrities like Aishwarya Rai Bachchan, Bella Hadid and more have adopted the unlikely breakout trend—the hooded dress—that has its roots deep in the runways of the ‘80s and street style scene of the ‘90s. The hooded dress is dominating the fashion scene today. With robust backing from the fashion mavens like Kate Moss, Bella Hadid, Margot Robbie, Priyanka Chopra, Simone Ashley, and many more, the hooded dress has taken its official seat on the formal dress code this year. First spotted on the timeless icon Grace Jones who wore a custom purple hooded dress by couturier Azzedine Alaia in 1985, the hooded dress made its runway debut in Yves Saint Laurent’s Fall/Winter 1991 collection. <br /><br />For their Spring/Summer 2023 collection, Saint Laurent’s creative director Pieter Mulier chose to revive this perennial staple and style it with blackout sunglasses and oversized coats, giving us a true Parisian chic look. Soon the hooded dress flooded the runways of the biggest fashion houses from Tom Ford, Halpern, Schiaparelli, and many more. Instantly becoming a celebrity favourite, various versions of the hooded dress have proceeded to make their red carpet debut soon after. From movie premieres to the Met Gala, this fashion-forward silhouette has shown no signs of stopping. Read on as we list some recent notable celebrity appearances in this iconic silhouette, to further solidify our case for its resurgence and validate its addition into our wardrobe. <br /><br />Arriving at the 2023 Met Gala wearing a hooded dress by Valentino adorned with 3D camellia flowers all over, the singer channelled every bit of the main character energy via her look. <br /> At the Cannes Film Festival, actor and Loreal ambassador Aishwarya Rai Bachchan made another unexpected appearance in a metallic hooded gown by Sophie Couture. The actor kept the rest of her styling minimal with a bold lip and a sleek middle-part hairdo. <br /> Blackpink’s Rose attended the LACMA Gala wearing a cutout hooded gown by Saint Laurent. She accessorised the crossed bodice, ruched skirt dress with golden accents and finished her styling out with a statement braid. <br /> At the Bulgari party in Venice at Palazzo Ducale, Anne Hathaway continued her winning sartorial streak wearing a bejewelled Versace hooded dress. With a thigh-high slit that shows off her silver mirror platform heels, the actor’s look was refreshing yet striking. <br />  </p>
      <p className='w-[80%] mx-auto mt-5 text-2xl font-bold'>By DEVKI BHATT</p>
    </div>
  )
}
