import React from 'react'
import m1 from '../assets/m1.avif'

export default function Mpage1() {
  return (
    <div>
      <img className='w-[65%] mx-auto h-[30%]' src={m1} alt="" />
      <p className='w-[80%] text-slate-600 mt-10 mx-auto'  >When we rest our attention on what we’re seeing, smelling, tasting, touching, or hearing, we can begin to ground ourselves and feel fully present. <br /> <br /> If we draw from a pool of resources without replenishing them, we can begin to feel depleted—our brain gets sluggish, and we don’t make good decisions. By resting our attention on our senses, we are taking a moment to reconnect with ourselves and feel fully present. <br /> <br /> In this practice, we’re going to replenish our mental energy by returning to our senses, literally. By focusing on our senses, we can rest our attention on what we’re seeing, smelling, tasting, touching, or hearing. <br /> <br /> <br /> <span className='text-lg font-bold' >Find a supported posture.</span>You can do this practice while walking or sitting. You can also take this practice outside if you have access to a quiet space. Lower your gaze or close your eyes—if you’re not walking. <br /> <span className='text-lg font-bold' >Start with the sense of touch.</span>Feel any sensations of touch in your feet and the contact they make with the floor. Can you feel the touch of any footwear, or if you’re barefoot, the touch of air on your skin? Where else in your body can you feel the air touching your skin? <br /> <span className='text-lg font-bold' >Now shift your attention to sound.</span> Notice the sounds in your environment or within you. Note how some sounds may feel pleasant, some are unpleasant, and some are neutral. You may discover that your mind has wandered, and that’s natural. As soon as you notice that, return to your sense of sound and receive the sounds with kindness. You can choose to stay with your sense of touch or sound, or you can shift your attention now to smell. <br /> <span className='text-lg font-bold' >Notice the scents around you.</span>  If you’re outdoors, you may discover very different scents than what you find inside your house or office. With spaciousness in your mind and body, receive any scents or absence of scents. As we refine our ability to smell, staying here open and receptive, we may start to uncover newer scents that we had not noticed earlier. Stay here for a few more moments. You can choose to stay here with the sense of smell or return to your sense of touch or sound. <br /> <span className='text-lg font-bold' >Open your eyes and look at an object in front of you with fresh eyes.</span> Without getting lost in labels or judgments, see the object as if you’re looking at it for the first time. Note the textures, colors, lightness, darkness. Make a note of how it feels to give your full attention to your senses. </p>
      <p className='w-[80%] mx-auto mt-5 text-2xl font-bold'>By SHALINI BAHL-MILNE</p>
    </div>
  )
}
