import React from 'react'
import m2 from '../assets/m2.jpg'

export default function Mpage2() {
  return (
    <div>
            <img className='w-[65%] mx-auto h-[30%]' src={m2} alt="" />
            <p className='w-[80%] text-slate-600 mt-10 mx-auto'>All of us can feel the impact of these uncertain and challenging times on our hearts and in our nervous systems. While there are parts of our current crisis that we cannot control, that doesn’t mean we’re powerless. When we’re up against change, uncertainty, and stress, resilience is the key to navigating life and emerging with more happiness and satisfaction. <br /> <br /> We can cultivate resilience through the practices of mindfulness and compassion. This is the miracle of neuroplasticity—what you practice grows stronger. We can carve out pathways of greater clarity, courage, and compassion through practice. <br /> <br />The five steps below help us face difficult emotions, re-center, and find calm. These steps don’t have to be done perfectly. Think direction, not destination. The key is practice. <br /><br /><br /><span className='text-lg font-bold' >NAME IT TO TAME IT</span> <br /> It’s helpful to remember that our emotions are here for a reason. They often serve as a smoke alarm, letting us know about an impending fire. When we ignore or repress our emotions, it can lead to bigger problems. <br /> Mindfulness teaches us a different way to manage difficult emotions—to acknowledge and name what we feel. This is called “name it to tame it.” Research shows that when we acknowledge and name our emotions it allows the body to physiologically calm down. Naming an emotion puts the brakes on your reactivity, down-regulates the nervous system, and allows you to see clearly. <br /> <br /> <span className='text-lg font-bold' > WELCOME YOUR EMOTIONS</span> <br /> Emotions have a limited time span, typically lasting for only thirty to ninety seconds. They arise, do their dance, and pass away, just like waves in the ocean. When we remember that this painful feeling will not last forever, it becomes more manageable. <br /> Through practice, we can learn to welcome all of our emotions with an attitude of kindness and curiosity. This involves becoming interested in the emotion and the felt experience in the body. For example, you may feel sadness as a tightening in your throat, or fear as a contraction in your belly. All emotions have a signature in the body. <br /> <br /></p>
            <p className='w-[80%] mx-auto mt-5 text-2xl font-bold'>By SHAUNA SHAPIRO</p>
  </div>
  )
}
