import React from 'react'
import t2 from '../assets/t2.webp'


export default function Tpage2() {
  return (
    <div>
      <img className='w-[65%] mx-auto h-[30%]' src={t2} alt="" />
      <p className='w-[80%] text-slate-600 mt-10 mx-auto' >They were innovators. Their goal was audacious. It was to provide a way for the many different kinds of networks being invented to talk to each other. These pioneers collaborated, building upon each other’s work, pushing the boundaries of what was possible. They opened up a new world of opportunity for the future of humanity. <br /> <br /> They were visionaries, but the vision may have seemed mad to some. Yet they believed billions of people would come to rely daily on their development: the Internet. And so here we are. The Internet has become a powerful, transformative force. It is easy to forget how much it has changed many societies for the better. Put simply, many people in the world can no longer function without it. But as each year passes, the Internet faces more and more threats. <br /> <span className='text-lg text-[#7e245c] font-bold'>We must do everything in our power to protect the open, global Internet—before there is nothing left to protect.</span> <br />As so often happens with such a valuable resource, powerful forces are trying to wrest control of it, exploiting it for their own gain. As you are reading these very words, the Internet is under existential threat. There are people working to harm the attributes that make it work, proposing and enacting policies that are both misguided and shortsighted. There are others trying to impose nation-state borders on technical systems designed to avoid such boundaries. This splinters the Internet into fragments that are only a shadow of the true, global Internet. Still others are plotting to disrupt access and the free flow of information, suppressing human expression through Internet shutdowns. <br /> We must defend against these emerging threats now. We must ensure that this human technology remains in the hands of humans, and not those who wish to control it to further their own agenda or those who will break it through misunderstanding. <br /> Our Action Plan 2023 outlines how we will address these challenges head on, so that the Internet can be a resource for everyone, forever. Working in collaboration with you—our global community of partners, members, and champions—we will take specific, measurable actions to build, and defend the Internet. As with everything we do, we cannot do it alone. The Internet needs all of us to protect its future. Because its future is now intertwined with humanity’s.</p>
      <p className='w-[80%] mx-auto mt-5 text-2xl font-bold'>By Andrew Sullivan</p>
    </div>
  )
}
