import React from 'react'
import tr3 from '../assets/tr3.jpg'

export default function Trpage3() {
  return (
    <div>
      <img className='w-[65%] mx-auto h-[30%]' src={tr3} alt="" />
      <p className='w-[80%] text-slate-600 mt-10 mx-auto'  >Arrival
          Our miserable flights with no entertainment or reclining seats from Malaga via Casablanca landed in Accra at 4:30 AM. After Peggy’s herculean month-long navigation of the visa process, we were expecting more red tape at entry, but the 10-minute immigration process was efficient and friendly. We would never doctor our 15-year old yellow fever vaccine cards to enter the country - because that would be wrong. <br /> <br /> We walked the km to the Marriott booked with Peggy’s platinum status. I was exhausted but still a bit bothered by passing people sleeping in the streets on our way to luxury. We then slept till the afternoon and walked downtown to explore. Other than a couple busy intersections it was a pleasant enough walk on wide avenues with dirt path shoulders and by several embassies. <br /> Phone/Internet Service: Anyone traveling abroad with a locked iPhone should consider using an e-sim card. I bought a gig of data to use over a 10-day period and it worked anytime I had cell service. I limited my data use to Google Maps, WhatsApp, and internet browsing and I only used 1 gig during my time here. Just Google ‘esim airalo.’ <br /> Independence / Black Star Square: It took an hour to walk from the airport area to Black Star Square, which has monuments honoring Ghana’s 1957 independence from the British. It’s worth checking out. They asked for a donation to climb the tower but we didn’t have any small bills. When we tried to climb over a guardrail (my idea) to get to a path along the side of the road, someone who worked at the independence memorial whistled and shook his head. <br /> The Sludge
          Accra’s neighborhoods are colorful, lively, friendly, and relatively devoid of Western influence (except for KFC). I enjoyed aspects of the scene - everyone outside mingling, soccer games on dirt fields, shops with every religious name imaginable. I remember someone telling me years ago that Accra was difficult to enjoy because of the smell of the open drainage sewers and I dismissed it as an ugly Americanism. But I admit it made it very difficult to enjoy since the smell of putrid sludge in the gutters was inescapable in the city center. Maybe it’s only there during the rainy season. The locals seem inured to it since the shops on both sides of the street are right above the sludge, but I couldn’t help but walk in the middle of the street when possible to minimize the risk of catching a whiff. Obviously the locals would get rid of it if they could, so this isn’t a judgment of the culture or people but a reality check of the tourist experience. <br /> Osu
          Then we walked to the Osu neighborhood to eat at Tatale, a terrific vegan restaurant by any standard. After our trip to Wli we stayed in the area and ate there again. Based on the description in the guide book, we expected that the area around Oxford Street would be full of young, educated, middle-class Ghanians at chic cafes and bars, but aside from a few ethnic restaurants, it was much like the rest of the center. The sludge smell was everywhere at street level, so we went to a rooftop bar to have a drink, but it felt wrong to drink a cocktail the same price as most locals’ weekly pay. <br /> Bus Stations
          Longer transits were pretty difficult on this trip, so I don’t mince words below. But keep in mind that Peggy and I pride ourselves on traveling like locals by using buses, tro-tros, and shared taxis, so we visited areas of the city that most tourists probably don’t venture. And despite all the things that I can’t unsee or unsmell, we never once felt the least bit in danger, despite the fact that we were collectively carrying 500USD, enough to radically change the lives of most of the people we encountered. <br /> <br /> Entering Tudu station was like a scene from a war movie. Mobs of people were pounding on the taxi windows and yelling the prices of their bus tickets as the driver tried to enter while others taxis were trying to leave. There was nothing dangerous or threatening about it - just chaos. We were nonetheless thankful that our driver persevered and got us inside the gates. <br />Buying tickets was quite the process. We mostly got by in Ghana speaking simple English and picking out important words in their pidgin English, but we had to ask the woman at the window to repeat herself several times because she was asking bizarre questions like how old we are and insisting on us providing any Ghanian phone number to get a bus ticket. <br /> <br />After that plenty of non-helpers swarmed to offer their non-help. One guy looked completely dejected when we said we didn’t have any luggage, but then I made the mistake of asking him where the bathroom was and got scammed out of a dollar, which was no big deal. <br /> <br /> After our second trip to Accra we went to Circle Station, which was far worse. The ‘station,’ which was basically a cluster of buses, tro-tros, tents, and general squalor, was under a highway overpass shaped like a circle. Families of homeless Muslim refugees (from Burkina Faso? - apparently there’s been a major crisis there that the international media hasn’t picked up at all) were asleep or huddled together under the overpass avoiding the rain. We couldn’t figure out where the bus was so we had to wander around for 20 minutes before taking a short taxi trip through slums with people destitute and some naked. <br /> <br /> We got to the bus just at its noon departure time but we still sat there for another hour or so before leaving. <br />After this I was able to convince Peggy not to spend another night in Accra and just go to the airport in a private taxi on the morning of our flight. <br /> Again, everyone was extremely friendly and welcoming, we never felt unsafe for a second, the culture is strong, the (non-Jesus) music is fabulous, and the food is delicious. I just couldn’t get past the assault on my senses, and I’m no stranger to Africa or poverty. <br /> </p>
      <p className='w-[80%] mx-auto mt-5 text-2xl font-bold'>By Bellini</p>
    </div>
  )
}
